### PR TITLE
:rocket: Log to stdout using bunyan

### PR DESCRIPTION
**Pull request by adamgraves-choices**

### CODE REVIEW

**Comment by c2s-dev** [comment]
:rocket: deployed to [http://gp-finder-pr-38.dev.c2s.nhschoices.net](http://gp-finder-pr-38.dev.c2s.nhschoices.net)

**Comment by st3v3nhunt** [comment]
@adamgraves-choices Please rebase the 3 commits made so far into 1 too. There is no need for the extra info to be included in the history.

As far as shrinkwrap goes, it gets updated by `npm`. If you clear out the `node_modules`, run `npm install` and then install bunyan via `npm install bunyan --save` and uninstall `nhsuk-bunyan-logger` via `npm uninstall nhsuk-bunyan-logger --save` the shrinkwrap should be sorted.

**Comment by c2s-dev** [comment]
:warning: deployment of 38 for nhsuk/gp-finder failed

**Comment by c2s-dev** [comment]
:rocket: deployed to [http://gp-finder-pr-38.dev.c2s.nhschoices.net](http://gp-finder-pr-38.dev.c2s.nhschoices.net)

**Comment by c2s-dev** [comment]
:rocket: deployed to [http://gp-finder-pr-38.dev.c2s.nhschoices.net](http://gp-finder-pr-38.dev.c2s.nhschoices.net)

**Comment by beseven** [comment]
@adamgraves-choices - can you rebase pls?

**Comment by adamgraves-choices** [comment]
I'm going to close this, as @st3v3nhunt is doing it.

**Pull request closed without merging**
