### PR TITLE
:information_desk_person: few style tweeks

### PR DESCRIPTION
**Pull request by ajthomascouk**

### CODE REVIEW

**Comment by c2s-dev** [comment]
:rocket: deployed to [http://gp-finder-pr-68.dev.c2s.nhschoices.net](http://gp-finder-pr-68.dev.c2s.nhschoices.net)

**Comment by c2s-dev** [comment]
:rocket: deployed to [http://gp-finder-pr-68.dev.c2s.nhschoices.net](http://gp-finder-pr-68.dev.c2s.nhschoices.net)

**Comment by ermlikeyeah** [comment]
The are several colours of red on the warning pattern rather than one.

The left hand margin is #d81e05.

The warning text is #d81e05.

The text field margin is #b10e1e, which seems to be overriding #d81e05.

These need to be the same red, and a red that is in the palette.

**Comment by c2s-dev** [comment]
:rocket: deployed to [http://gp-finder-pr-68.dev.c2s.nhschoices.net](http://gp-finder-pr-68.dev.c2s.nhschoices.net)

**Comment by c2s-dev** [comment]
:rocket: deployed to [http://gp-finder-pr-68.dev.c2s.nhschoices.net](http://gp-finder-pr-68.dev.c2s.nhschoices.net)

**Pull request merged**
