### PR TITLE
Allow name _and_ postcode search

### PR DESCRIPTION
**Pull request by neilbmclaughlin**
Todo

- [x] Remove duplication of ES should clause which occurs in both the query building methods.
- [x] Move logic for messaging dependent on search type ( postcode/outcode and/or name) out of templates and into testable lib used by middleware. For example, _We found these surgeries close to the 'HG5' area using 'Beech House'_
- [ ] Review message wording

### CODE REVIEW

**Comment by c2s-dev** [comment]
:rocket: deployment of gp-finder succeeded (http://gp-finder-pr-154.dev.beta.nhschoices.net)

**Comment by c2s-dev** [comment]
:rocket: deployment of gp-finder succeeded (http://gp-finder-pr-154.dev.beta.nhschoices.net)

**Comment by c2s-dev** [comment]
:rocket: deployment of gp-finder succeeded (http://gp-finder-pr-154.dev.beta.nhschoices.net)

**Comment by c2s-dev** [comment]
:rocket: deployment of gp-finder succeeded (http://gp-finder-pr-154.dev.beta.nhschoices.net)

**Comment by c2s-dev** [comment]
:rocket: deployment of gp-finder succeeded (http://gp-finder-pr-154.dev.beta.nhschoices.net)

**Comment by c2s-dev** [comment]
:rocket: deployment of gp-finder succeeded (http://gp-finder-pr-154.dev.beta.nhschoices.net)

**Comment by c2s-dev** [comment]
:rocket: deployment of gp-finder succeeded (http://gp-finder-pr-154.dev.beta.nhschoices.net)

**Comment by c2s-dev** [comment]
:rocket: deployment of gp-finder succeeded (http://gp-finder-pr-154.dev.beta.nhschoices.net)

**Comment by beseven** [comment]
Happy to merge, and add the  Review message wording in the feature branch

**Pull request merged**
