### PR TITLE
:question: check to see the prs are working

### PR DESCRIPTION
**Pull request by beseven**

### CODE REVIEW

**Comment by c2s-dev** [comment]
:rocket: deployed to [http://gp-finder-pr-6.dev.c2s.nhschoices.net](http://gp-finder-pr-6.dev.c2s.nhschoices.net)

**Comment by c2s-dev** [comment]
:rocket: deployed to [http://gp-finder-pr-6.dev.c2s.nhschoices.net](http://gp-finder-pr-6.dev.c2s.nhschoices.net)

**Comment by beseven** [comment]
Rancher upgraded and ready to re-review

**Comment by c2s-dev** [comment]
:rocket: deployed to [http://gp-finder-pr-6.dev.c2s.nhschoices.net](http://gp-finder-pr-6.dev.c2s.nhschoices.net)

**Comment by beseven** [comment]
@neilbmclaughlin Do you want me to force rebase, to ger rif of some of the buggy commits?

**Pull request merged**
