### PR TITLE
:cyclone: word searching, equal weigthing

### PR DESCRIPTION
**Pull request by beseven**

### CODE REVIEW

**Comment by c2s-dev** [comment]
:rocket: deployed to [http://gp-finder-pr-40.dev.c2s.nhschoices.net](http://gp-finder-pr-40.dev.c2s.nhschoices.net)

**Comment by c2s-dev** [comment]
:rocket: deployed to [http://gp-finder-pr-40.dev.c2s.nhschoices.net](http://gp-finder-pr-40.dev.c2s.nhschoices.net)

**Comment by beseven** [comment]
Uses nhsuk/profiles-db#20 / cc @neilbmclaughlin

**Comment by c2s-dev** [comment]
:warning: deployment of 40 for nhsuk/gp-finder failed

**Comment by c2s-dev** [comment]
:rocket: deployed to [http://gp-finder-pr-40.dev.c2s.nhschoices.net](http://gp-finder-pr-40.dev.c2s.nhschoices.net)

**Comment by beseven** [comment]
This ranked (pun intended) higher when shown to the product owner with the caveat that the next step is to remove duplicates in the ETL / @neilbmclaughlin

**Comment by c2s-dev** [comment]
:rocket: deployed to [http://gp-finder-pr-40.dev.c2s.nhschoices.net](http://gp-finder-pr-40.dev.c2s.nhschoices.net)

**Comment by c2s-dev** [comment]
:rocket: deployed to [http://gp-finder-pr-40.dev.c2s.nhschoices.net](http://gp-finder-pr-40.dev.c2s.nhschoices.net)

**Pull request merged**
