### PR TITLE
:leaves: phrase searching, weighted by name

### PR DESCRIPTION
**Pull request by beseven**

### CODE REVIEW

**Comment by c2s-dev** [comment]
:rocket: deployed to [http://gp-finder-pr-37.dev.c2s.nhschoices.net](http://gp-finder-pr-37.dev.c2s.nhschoices.net)

**Comment by c2s-dev** [comment]
:warning: deployment of 37 for nhsuk/gp-finder failed

**Comment by c2s-dev** [comment]
:warning: deployment of 37 for nhsuk/gp-finder failed

**Comment by beseven** [comment]
Uses https://github.com/nhsuk/profiles-db/pull/13 / cc @neilbmclaughlin

**Comment by c2s-dev** [comment]
:rocket: deployed to [http://gp-finder-pr-37.dev.c2s.nhschoices.net](http://gp-finder-pr-37.dev.c2s.nhschoices.net)

**Pull request closed without merging**
