### PR TITLE
Use PostcodeIO-Client promises

### PR DESCRIPTION
**Pull request by neilbmclaughlin**
The tests currently fail due to the change to promises and I'm exploring how to write tests for promises based code.

I've been focusing on getting just one test to pass in order to understand how the others might be written.

You can run this test with:
```
LOG_LEVEL=20 yarn test-unit -- --watch --grep 'when postcode.io is not available'
```

### CODE REVIEW

**Comment by neilbmclaughlin** [comment]
The tests currently fail due to the change to promises and I'm exploring how to write test for promises based code.

I've been focusing on getting just one test to pass in order to understand how the others might be written.

You can run this test with `LOG_LEVEL=20 yarn test-unit -- --watch --grep 'when postcode.io is not available'`

**Comment by neilbmclaughlin** [comment]
Got a bit further by adding the missing return to ensure a promise is returned.
The tests now pass and the order of things is as expected. 

The `expect` in the rendererFake.postcodeError is commented out as, with it in, 
an unhandled reject message is displayed.

Still more work to do.

**Comment by neilbmclaughlin** [comment]
No longer have unhandled reject and test is failing for a good reason. Need to find out what postcodeError is called with

**Comment by c2s-dev** [comment]
:rocket: deployment of nhsuk/gp-finder succeeded (http://gp-finder-pr-190.dev.beta.nhschoices.net)

**Comment by c2s-dev** [comment]
:rocket: deployment of nhsuk/gp-finder succeeded (http://gp-finder-pr-190.dev.beta.nhschoices.net)

**Comment by c2s-dev** [comment]
:rocket: deployment of nhsuk/gp-finder succeeded (http://gp-finder-pr-190.dev.beta.nhschoices.net)

**Comment by c2s-dev** [comment]
:rocket: deployment of nhsuk/gp-finder succeeded (http://gp-finder-pr-190.dev.beta.nhschoices.net)

**Comment by c2s-dev** [comment]
:rocket: deployment of nhsuk/gp-finder succeeded (http://gp-finder-pr-190.dev.beta.nhschoices.net)

**Pull request merged**
