### PR TITLE
Allow setting of container scale with ENV variable

### PR DESCRIPTION
**Pull request by adamgraves-choices**

### CODE REVIEW

**Comment by c2s-dev** [comment]
:warning: deployment of nhsuk/gp-finder failed

**Comment by neilbmclaughlin** [comment]
I rebased this and have just got a failed build comment in the PR despite the 'all checks passed'.

There are errors in the Travis log but looked at why yet.

There are unrelated non failing cover coverage errors in the build log  which I've logged as an issue.

**Comment by neilbmclaughlin** [comment]
@adamgraves-choices - can you take a look and let me know if this is good to be merged given the deployment failure message.

**Comment by neilbmclaughlin** [comment]
The travis log has the following error:
```
Deploying rancher stack gp-finder-pr-189 in environment nhsuk-dev
time="2017-08-01T20:54:32Z" level=error msg="Could not parse config for project gp-finder-pr-189 : Invalid interpolation format for key \"scale\": \"${INITIAL_CONTAINER_SCALE:1}\"" 
time="2017-08-01T20:54:32Z" level=fatal msg="Failed to read project: Invalid interpolation format for key \"scale\": \"${INITIAL_CONTAINER_SCALE:1}\"" 
{"id":"456bf4b6-efee-45bd-93ab-5b6adf27e82c","type":"error","links":{},"actions":{},"status":405,"code":"Method not allowed","message":"Method not allowed","detail":null,"baseType":"error"}Comment ':warning: deployment of nhsuk/gp-finder failed' added to pr 189 on nhsuk/gp-finder

travis_time:end:0e04ca3f:start=1501620816513194715,finish=1501620874311223742,duration=57798029027
```

**Comment by c2s-dev** [comment]
:rocket: deployment of nhsuk/gp-finder succeeded (http://gp-finder-pr-189.dev.beta.nhschoices.net)

**Pull request merged**
