### PR TITLE
Frontend/disable autocomplete

### PR DESCRIPTION
**Pull request by ajthomascouk**

### CODE REVIEW

**Comment by c2s-dev** [comment]
:rocket: deployment of gp-finder succeeded (http://gp-finder-pr-169.dev.beta.nhschoices.net)

**Comment by ajthomascouk** [comment]
[Investigate switching off autocomplete on input boxes](https://trello.com/c/MgZAJPM5/698-investigate-switching-off-autocomplete-on-input-boxes)

**Comment by neilbmclaughlin** [comment]
@ajthomascouk - what is happening with this PR? Can it be merged or does it require further work.

**Comment by ajthomascouk** [comment]
@ermlikeyeah wanted to do some further work around the impact of implementing `autocorrect`.

**Comment by neilbmclaughlin** [comment]
Closing for now. We can always reopen.

**Pull request closed without merging**
