### PR TITLE
Feature/change to es

### PR DESCRIPTION
**Pull request by st3v3nhunt**

### CODE REVIEW

**Comment by c2s-dev** [comment]
:rocket: deployment of gp-finder-pr-110 in nhsuk-dev succeeded (http://gp-finder-pr-110.dev.beta.nhschoices.net)

**Comment by c2s-dev** [comment]
:rocket: deployment of gp-finder-pr-110 in nhsuk-dev succeeded (http://gp-finder-pr-110.dev.beta.nhschoices.net)

**Comment by neilbmclaughlin** [comment]
Just comparing results with the live version and noticed that highlighting is not working the same. See a search of 'ireland wood surgery' as an example.

Will take a look at this on Monday.

**Comment by st3v3nhunt** [comment]
Superseded by #122

**Pull request closed without merging**
