### PR TITLE
Use latest CI scripts

### PR DESCRIPTION
**Pull request by neilbmclaughlin**

### CODE REVIEW

**Comment by c2s-dev** [comment]
:rocket: deployed to [http://gp-finder-pr-29.dev.c2s.nhschoices.net](http://gp-finder-pr-29.dev.c2s.nhschoices.net)

**Comment by c2s-dev** [comment]
:rocket: deployed to [http://gp-finder-pr-29.dev.c2s.nhschoices.net](http://gp-finder-pr-29.dev.c2s.nhschoices.net)

**Comment by neilbmclaughlin** [comment]
The CI build is showing the following error:

> `Version mismatch: file ./docker-compose-tests.yml specifies version 2.1 but extension file /home/travis/build/nhsuk/gp-finder/docker-compose.yml uses version 2.0`

This is because the local docker-compose.yml is overwritten by the one from the catalog which specifies version 2.0. This problem can probably be resolved by using `rancher catalog install`

**Comment by neilbmclaughlin** [comment]
No longer needed.

**Pull request closed without merging**
