### PR TITLE
Feature/more fe changes

### PR DESCRIPTION
**Pull request by ajthomascouk**
I've added the 'experimental' tag. Not sure if thats the right thing to do.

### CODE REVIEW

**Comment by c2s-dev** [comment]
:rocket: deployed to [http://gp-finder-pr-20.dev.c2s.nhschoices.net](http://gp-finder-pr-20.dev.c2s.nhschoices.net)

**Comment by beseven** [comment]
I dissagree that this is experimental.

**Comment by c2s-dev** [comment]
:warning: deployment of 20 for nhsuk/gp-finder failed

**Comment by c2s-dev** [comment]
:rocket: deployed to [http://gp-finder-pr-20.dev.c2s.nhschoices.net](http://gp-finder-pr-20.dev.c2s.nhschoices.net)

**Comment by c2s-dev** [comment]
:rocket: deployed to [http://gp-finder-pr-20.dev.c2s.nhschoices.net](http://gp-finder-pr-20.dev.c2s.nhschoices.net)

**Comment by c2s-dev** [comment]
:rocket: deployed to [http://gp-finder-pr-20.dev.c2s.nhschoices.net](http://gp-finder-pr-20.dev.c2s.nhschoices.net)

**Pull request merged**
