### PR TITLE
:ship: Use normal user to run image

### PR DESCRIPTION
**Pull request by adamgraves-choices**

### CODE REVIEW

**Comment by beseven** [comment]
Seems root is required to create for the coverage.
`NODE_ENV=test istanbul "cover" "_mocha" "--" "--recursive"
/code/node_modules/mkdirp/index.js:90
                    throw err0;
                    ^
Error: EACCES: permission denied, mkdir '/code/coverage'`

@st3v3nhunt / @markysoft , as this is a similar issue as on `profiles` is it possible to create and check in the /code/coverage directory and only ignore the contents? Would that solve the issue?

**Comment by c2s-dev** [comment]
:rocket: deployed to [http://gp-finder-pr-36.dev.c2s.nhschoices.net](http://gp-finder-pr-36.dev.c2s.nhschoices.net)

**Comment by adamgraves-choices** [comment]
@beseven Updating docker-compose to use the root user has fixed the build.

**Comment by c2s-dev** [comment]
:rocket: deployed to [http://gp-finder-pr-36.dev.c2s.nhschoices.net](http://gp-finder-pr-36.dev.c2s.nhschoices.net)

**Comment by c2s-dev** [comment]
:rocket: deployed to [http://gp-finder-pr-36.dev.c2s.nhschoices.net](http://gp-finder-pr-36.dev.c2s.nhschoices.net)

**Pull request merged**
