### PR TITLE
Remove travis env vars

### PR DESCRIPTION
**Pull request by neilbmclaughlin**

### CODE REVIEW

**Comment by c2s-dev** [comment]
:warning: deployment of 51 for nhsuk/gp-finder failed

**Comment by c2s-dev** [comment]
:warning: deployment of 51 for nhsuk/gp-finder failed

**Comment by neilbmclaughlin** [comment]
CI broken https://github.com/nhsuk/nhsuk-rancher-templates/pull/46

**Comment by st3v3nhunt** [comment]
I've restarted the PR build in the hope it the deployment will work now https://github.com/nhsuk/nhsuk-rancher-templates/pull/46 has been merged

**Comment by c2s-dev** [comment]
:rocket: deployed to [http://gp-finder-pr-51.dev.c2s.nhschoices.net](http://gp-finder-pr-51.dev.c2s.nhschoices.net)

**Pull request merged**
