### PR TITLE
Feature/search suggest enhancements

### PR DESCRIPTION
**Pull request by beseven**

### CODE REVIEW

**Comment by c2s-dev** [comment]
:rocket: deployment of gp-finder-pr-91 in nhsuk-dev succeeded (http://gp-finder-pr-91.dev.beta.nhschoices.net)

**Comment by c2s-dev** [comment]
:rocket: deployment of gp-finder-pr-91 in nhsuk-dev succeeded (http://gp-finder-pr-91.dev.beta.nhschoices.net)

**Comment by c2s-dev** [comment]
:rocket: deployment of gp-finder-pr-91 in nhsuk-dev succeeded (http://gp-finder-pr-91.dev.beta.nhschoices.net)

**Comment by c2s-dev** [comment]
:rocket: deployment of gp-finder-pr-91 in nhsuk-dev succeeded (http://gp-finder-pr-91.dev.beta.nhschoices.net)

**Comment by beseven** [comment]
Client side JS tests on hold for now

**Pull request closed without merging**
